version: "3.8"

networks: 
  promise:
    driver: bridge

services:
  nginx:
    container_name: promise-nginx
    image: nginx:alpine
    restart: always

  node:
    container_name: promise-node
    depends_on: 
      - redis
    environment:
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
    image: node
    networks: 
      - promise
    ports: 
      - "8080:8080"

  postgres:
    container_name: promise-postgres
    env_file: 
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    image: postgres:alpine
    networks: 
      - promise
    ports:
      - "5432:5432"
    restart: always
    volumes: 
      - /var/lib/postgresql/promise/data:/var/lib/postgresql/data

  redis:
    container_name: promise-redis
    depends_on: 
      - postgres
    image: redis:alpine
    networks: 
      - promise

volumes:
  postgres:
