version: "3.8"

services:
  postgres:
    container_name: promise-postgres
    env_file: 
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      interval: 5s
      retries: 3
      start_period: 10s
      test: ["CMD", "pg_isready"]
      timeout: 5s
    image: postgres:alpine
    ports:
      - "5432:5432"
    restart: always
    user: ${POSTGRES_USER}
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    container_name: promise-redis
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      interval: 5s
      retries: 3
      start_period: 10s
      test: ["CMD", "redis-cli", "ping"]
      timeout: 3s
    image: redis:alpine
    networks:
      - server
    ports:
      - "6379:6379"
    restart: always

  worker:
    container_name: promise-worker
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    image: golang:1.16-alpine
    ports: 
      - "5000:5000"
    networks: 
      - server

networks:
  server:

volumes:
  postgres: